/* ==========================================================================
   Lumina Jewelry — Server-side price list
   The checkout function prices every order from THIS file, never from the
   browser, so a tampered cart cannot change what a customer is charged.

   Regenerated by the admin panel whenever you publish a catalogue change —
   it ships inside the site-update zip. Keep it in step with
   assets/js/data.js; if a handle is missing here, checkout rejects the order.
   ========================================================================== */
module.exports = {
  "aurora-solitaire-ring": { "name": "Aurora Solitaire Ring", "price": 1890 },
  "celeste-pave-band": { "name": "Celeste Pavé Band", "price": 745 },
  "eclat-signet-ring": { "name": "Éclat Signet Ring", "price": 520 },
  "heritage-twist-ring": { "name": "Heritage Twist Ring", "price": 385 },
  "aurora-eternity-band": { "name": "Aurora Eternity Band", "price": 1420 },
  "aurora-drop-pendant": { "name": "Aurora Drop Pendant", "price": 1250 },
  "celeste-constellation-necklace": { "name": "Celeste Constellation Necklace", "price": 890 },
  "eclat-herringbone-chain": { "name": "Éclat Herringbone Chain", "price": 640 },
  "heritage-locket": { "name": "Heritage Locket", "price": 470 },
  "celeste-lariat-necklace": { "name": "Celeste Lariat Necklace", "price": 720 },
  "aurora-teardrop-earrings": { "name": "Aurora Teardrop Earrings", "price": 980 },
  "celeste-halo-studs": { "name": "Celeste Halo Studs", "price": 560 },
  "eclat-hoop-earrings": { "name": "Éclat Hoop Earrings", "price": 420 },
  "heritage-pearl-drops": { "name": "Heritage Pearl Drops", "price": 340 },
  "eclat-ear-cuff": { "name": "Éclat Ear Cuff", "price": 260 },
  "aurora-tennis-bracelet": { "name": "Aurora Tennis Bracelet", "price": 2450 },
  "celeste-chain-bracelet": { "name": "Celeste Chain Bracelet", "price": 680 },
  "eclat-cuff": { "name": "Éclat Cuff", "price": 890 },
  "heritage-charm-bracelet": { "name": "Heritage Charm Bracelet", "price": 395 },
  "heritage-bangle": { "name": "Heritage Bangle", "price": 540 }
};
